---
openapi: 3.0.1
info:
  title: Tasklytic API
  description: A comprehensive task management and productivity tracking API
  version: v1
  contact:
    name: Tasklytic Team
    email: support@tasklytic.com
paths:
  "/users/sign_in":
    post:
      summary: User login
      tags:
      - Authentication
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      format: email
                      example: "user@example.com"
                    password:
                      type: string
                      format: password
                      example: "password123"
                  required:
                  - email
                  - password
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Signed in successfully"
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      email:
                        type: string
                      first_name:
                        type: string
                      last_name:
                        type: string
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid email or password"
  "/users/sign_out":
    delete:
      summary: User logout
      tags:
      - Authentication
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Logout successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Signed out successfully"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Unauthorized"
  "/api/v1/projects":
    get:
      summary: retrieve_projects
      tags:
      - Projects
      security:
      - bearerAuth: []
      parameters:
      - name: page
        in: query
        required: true
        description: Page number
        schema:
          type: integer
      - name: per_page
        in: query
        required: false
        description: Items per page
        schema:
          type: integer
      - name: user_id
        in: query
        required: false
        description: Item per page
        schema:
          type: integer
      responses:
        '200':
          description: per_page cap
        '400':
          description: page param must be positive
    post:
      summary: create_project
      tags:
      - Projects
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: project created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                project:
                  type: object
                  properties:
                    name:
                      type: string
                    description:
                      type: string
                  required:
                  - name
  "/api/v1/projects/{id}":
    get:
      summary: Retrieves a project
      tags:
      - Projects
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: project found
        '404':
          description: project not found
        '400':
          description: Page parameter is required
    put:
      summary: Updates a project
      tags:
      - Projects
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: project updated
        '404':
          description: project not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                project:
                  type: object
                  properties:
                    name:
                      type: string
                    description:
                      type: string
    delete:
      summary: Deletes a project
      tags:
      - Projects
      security:
      - bearerAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: project deleted
        '404':
          description: project not found
  "/api/v1/tasks":
    get:
      summary: retrieve tasks
      tags:
      - Tasks
      security:
      - bearerAuth: []
      parameters:
      - name: page
        in: query
        required: true
        description: Page number
        schema:
          type: integer
      - name: per_page
        in: query
        required: false
        description: Per page
        schema:
          type: integer
      - name: project_id
        in: query
        required: false
        description: Project id of the tasks
        schema:
          type: integer
      responses:
        '200':
          description: tasks in descending order when project id is not given
servers:
- url: http://localhost:3000
  description: Development server
- url: https://api.tasklytic.com
  description: Production server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
- bearerAuth: []
